version: '3'
services:
  database: #image name
    image: database
    ports:
      - 3306:3306 #map port
  frontend: #image name
    image: frontend
    environment:
      API_URL: http://backend:8080
    ports:
      - 3000:3000 #map port
  backend: #image name
    image: backend
    environment:
      DB_HOST: database
      APP_PORT: 8080
    ports:
      - 8080:8080 #map port