FROM node:18.16-alpine3.17
# Installs latest Chromium (89) package.
RUN apk add --no-cache chromium
# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
WORKDIR /app
# COPY package*.json ./
# COPY yarn.lock ./
COPY . .
RUN yarn install
RUN yarn build start:prod
EXPOSE 8000 
CMD [ "node", "dist/main" ]

